<a href="https://colab.research.google.com/github/kuzovkov/neural-university/blob/main/%D0%91%D0%B0%D0%B7%D0%B0_%D0%B7%D0%BD%D0%B0%D0%BD%D0%B8%D0%B9_%7C_Label_Encoder_%7C_%D0%A3%D0%98%D0%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Label Encoder

---

 При решении задач машинного обучения, часто приходится иметь дело со строковыми параметрами. Чаще всего это категориальные фичи, например названия городов, цвета, должность итд. Некоторые библиотеки могут изначально работать со строковыми параметрами, но для большинства предварительно надо перевести буквы в цифры. Более того, это даже очень рекомендуется т.к. в числовом виде будет использоваться меньше оперативной памяти для хранения данных для обучения. Процесс перевода строковых данных (labels) в числовые данные называется label encoding.

# Рассмотрим пример использования LabelEncoder для датасета headhunter

In [ ]:
# Библиотека для скачивания файлов из Google Drive
import gdown

url = "https://drive.google.com/uc?id=1kK9BaJ8rx84BTCEvfYZl9MIuknsiqmzT"  # Ссылка на датасет headhunter
output = "hh.csv"                                                            # Название файла после скачивания
gdown.download(url, output, quiet=True)                                      # Скачивание файла

'hh.csv'

In [ ]:
# Импортруем библиотеку Pandas
import pandas as pd

df = pd.read_csv("/content/hh.csv").head(5)  # Смотрим что находится в базе
schedule = df['График'].unique()             # Сохраняем текстовый формат колонки "График"
df.head(5)                                   # Выводится первые 5 строк датасета

,Пол,Возраст,ЗП,Город,Занятость,График,Опыт (двойное нажатие для полной версии),Образование и ВУЗ,Ищет работу на должность
0,М,44,27000.0,малый или за пределами России город,полная занятость,полный день,73,среднее специальное,Старший администратор
1,М,42,60000.0,малый или за пределами России город,"частичная занятость, полная занятость","гибкий график, полный день",230,высшее,Старший IT инженер
2,М,45,65000.0,малый или за пределами России город,полная занятость,"полный день, удаленная работа",237,высшее,"Системный администратор, Системный инженер"
3,М,44,70000.0,Москва,полная занятость,"гибкий график, полный день, удаленная работа",69,высшее,"Web-программист, Web-администратор, Web-мастер"
4,М,41,45000.0,малый или за пределами России город,"частичная занятость, полная занятость","полный день, сменный график",161,высшее,Старший системный администратор \ начальник от...

В этом примере первый столбец (График) является полностью текстовым. Мы не можем использовать текст в данных для обучения модели. Поэтому, прежде чем мы сможем начать процесс, нам нужно эти данные подготовить.

 Для преобразования категорий в числовые данные используется класс LabelEncoder. Таким образом, чтобы получить признак для столбца "Занятость", импортируется класс из библиотеки sklearn и обработывается колонка функцией fit_transform.

In [ ]:
from sklearn import preprocessing                       # Импортируем модуль preprocessing в котором хранится LabelEncoder

label_encoder = preprocessing.LabelEncoder()            # Создаем объект label_encoder

df['График']= label_encoder.fit_transform(df['График']) # Кодируем колонку "График"

df.head(5)                                              # Выводится первые 5 строк датасета

,Пол,Возраст,ЗП,Город,Занятость,График,Опыт (двойное нажатие для полной версии),Образование и ВУЗ,Ищет работу на должность
0,М,44,27000.0,малый или за пределами России город,полная занятость,2,73,среднее специальное,Старший администратор
1,М,42,60000.0,малый или за пределами России город,"частичная занятость, полная занятость",0,230,высшее,Старший IT инженер
2,М,45,65000.0,малый или за пределами России город,полная занятость,4,237,высшее,"Системный администратор, Системный инженер"
3,М,44,70000.0,Москва,полная занятость,1,69,высшее,"Web-программист, Web-администратор, Web-мастер"
4,М,41,45000.0,малый или за пределами России город,"частичная занятость, полная занятость",3,161,высшее,Старший системный администратор \ начальник от...

Теперь, колонка "График" является закодированной с помощью LabelEncoder

In [ ]:
print(schedule)              # Текстовое представление признаков из колонки "График"
print(df['График'].unique()) # Закодированные значения для колонки "График"

['полный день' 'гибкий график, полный день'
 'полный день, удаленная работа'
 'гибкий график, полный день, удаленная работа'
 'полный день, сменный график']
[2 0 4 1 3]

Также, LabelEncoder можно использовать для одновременного кодирования нескольких столбцов.

In [ ]:
cols = ['Город', 'Занятость', 'Образование и ВУЗ', 'Ищет работу на должность'] # Названия колонок которые необходимо закодирвать

df[cols] = df[cols].apply(label_encoder.fit_transform)                        # Кодируются признаки сразу нескольких столбцов

df.head(5)                                                                     # Выводится первые 5 строк датасета

,Пол,Возраст,ЗП,Город,Занятость,График,Опыт (двойное нажатие для полной версии),Образование и ВУЗ,Ищет работу на должность
0,М,44,27000.0,1,0,2,73,1,3
1,М,42,60000.0,1,1,0,230,0,2
2,М,45,65000.0,1,0,4,237,0,1
3,М,44,70000.0,0,0,1,69,0,0
4,М,41,45000.0,1,1,3,161,0,4